# -*- coding: utf-8 -*-
"""bitirme.ipynb

Automatically generated by Colab.

    
"""

# -*- coding: utf-8 -*-
"""
Bitirme Projesi - Arıza Süre Tahmini
v4 — Tüm Düzeltmeler Entegre
"""

import pandas as pd
import numpy as np
import io, re
import scipy.sparse as sp
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split, KFold
from xgboost import XGBRegressor

import streamlit as st
import joblib
import os

@st.cache_resource # Modeli hafızada tutar, her etkileşimde tekrar okumaz
def model_ve_veriyi_yukle():
    if os.path.exists("egitilmis_model.pkl"):
        # Kayıtlı model varsa direkt yükle (Çok hızlıdır)
        return joblib.load("egitilmis_model.pkl")
    else:
        # Eğer dosya yoksa (İlk çalıştırma), burada eğitim fonksiyonunu çağırabilirsin
        # Şimdilik hata vermesi veya eğitimi başlatması için bir kontrol koyalım
        return None

# Uygulama açılırken paketi yükle
paket = model_ve_veriyi_yukle()

if paket:
    # Paketten bileşenleri geri çıkar
    model = paket["model"]
    vectorizer = paket["vectorizer"]
    kmeans = paket["kmeans"]
    # ... (Diğer tüm değişkenleri buradan çek)
    st.sidebar.success("Hazır model başarıyla yüklendi!")
else:
    st.sidebar.warning("Model dosyası bulunamadı, eğitim bekleniyor...")
# =====================================================
# 1. VERİ YÜKLEME
# =====================================================
import streamlit as st
import pandas as pd
import io
import os
# =====================================================
# 1. VERİ YÜKLEME (Streamlit Versiyonu)
# =====================================================

# Dosya yolunu tam olarak yazıyorsun
dosya_yolu = "verileriniz.xlsx"

if os.path.exists(dosya_yolu):
    df = pd.read_excel(dosya_yolu)
    # ... temizleme adımların ...
    st.success("Dosya yerel klasörden otomatik yüklendi.")
else:
    st.error("Dosya belirtilen yolda bulunamadı!")

df = df.iloc[:, 2:]
df.columns = df.iloc[0]
df = df.drop(0).reset_index(drop=True)
df.columns = df.columns.str.strip()

df["Süre_Dk"] = pd.to_numeric(df["Süre_Dk"], errors="coerce")
df = df.dropna(subset=["Süre_Dk", "Ariza_Aciklamasi", "Makine_Tipi"]).reset_index(drop=True)
print(f"Kayıt sayısı: {len(df)}")
# =====================================================
# 2. OUTLIER KIRPMA (IQR)
# =====================================================
Q1, Q3 = df["Süre_Dk"].quantile([0.25, 0.75])
IQR = Q3 - Q1
ust = Q3 + 2.5 * IQR
alt = max(1.0, Q1 - 1.5 * IQR)
print(f"Kırpma: Alt={alt:.1f} dk | Üst={ust:.1f} dk")
df["Süre_Dk_M"] = df["Süre_Dk"].clip(lower=alt, upper=ust)

# =====================================================
# 3. METİN TEMİZLEME
# =====================================================
ANLAMSIZ_TOKENLAR = {
    "zli", "lmesi", "ldi", "lmis", "lmak", "masi",
    "yardim", "arizasi", "ariza",
    "lar", "ler", "dan", "den", "nin", "nun", "bir", "ile"
}

def temizle(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r'\d+\s*(dk|dakika|dak|saat|sa|sn|saniye)\.?', '', text)
    text = re.sub(r'\d+', '', text)
    tr_map = str.maketrans("çğıöşüÇĞİÖŞÜ", "cgiosuCGIOSU")
    text = text.translate(tr_map)
    text = re.sub(r'[^\w\s]', ' ', text)
    tokens = [t for t in text.split() if t not in ANLAMSIZ_TOKENLAR and len(t) >= 4]
    return " ".join(tokens)

df["Temiz"] = df["Ariza_Aciklamasi"].apply(temizle)

df.head()

# =====================================================
# 4. TF-IDF
# =====================================================
vectorizer = TfidfVectorizer(
    max_features=150,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.60,
    sublinear_tf=True,
    token_pattern=r'\b[a-zA-Z]{4,}\b'
)
X_tfidf = vectorizer.fit_transform(df["Temiz"])
terms   = vectorizer.get_feature_names_out()
n_terms = len(terms)

# =====================================================
# 5. K-MEANS
# =====================================================
sure_log    = np.log1p(df["Süre_Dk_M"].values)
sure_scaled = (sure_log - sure_log.mean()) / sure_log.std()
SURE_WEIGHT = 2.0

X_for_cluster = sp.hstack([ #iki matrisi birleştirdik
    X_tfidf,
    sp.csr_matrix(sure_scaled.reshape(-1, 1) * SURE_WEIGHT)
], format="csr")

N_CLUSTERS = 10
kmeans = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=20)
df["Grup"] = kmeans.fit_predict(X_for_cluster).astype(str) #string tipinde olmalı ki ağırlık atamasın

dist = df["Grup"].value_counts().sort_index()
print("\nGrup dağılımı:")
for g, n in dist.items():
    bar = "█" * (n // 3)
    print(f"  Grup {g:>2}: {n:3d} kayıt  {bar}")

# =====================================================
# 6. TARGET ENCODING
# =====================================================
df["Süre_Dk_M_log"] = np.log1p(df["Süre_Dk_M"])
grup_mean_map   = df.groupby("Grup")["Süre_Dk_M"].mean().apply(np.log1p).to_dict()
makine_mean_map = df.groupby("Makine_Tipi")["Süre_Dk_M"].mean().apply(np.log1p).to_dict()
_global_mean_enc = np.log1p(df["Süre_Dk_M"].mean())

df["Grup_MeanEnc"]   = df["Grup"].map(grup_mean_map).fillna(_global_mean_enc).astype(float)
df["Makine_MeanEnc"] = df["Makine_Tipi"].map(makine_mean_map).fillna(_global_mean_enc).astype(float)

df.head()

# =====================================================
# 7. ÖZELLİK MATRİSİ
# =====================================================
makine_dummy = pd.get_dummies(df["Makine_Tipi"], prefix="mak")
grup_dummy   = pd.get_dummies(df["Grup"],        prefix="grup")
MAKINE_KOLONLARI = makine_dummy.columns.tolist()
GRUP_KOLONLARI   = grup_dummy.columns.tolist()

mean_enc_matrix = sp.csr_matrix(
    df[["Grup_MeanEnc", "Makine_MeanEnc"]].values.astype(float)
)

X_sparse = sp.hstack([
    sp.csr_matrix(makine_dummy.values.astype(float)),
    sp.csr_matrix(grup_dummy.values.astype(float)),
    mean_enc_matrix,
    X_tfidf
], format="csr")

y_log = np.log1p(df["Süre_Dk_M"].values)




# =====================================================
# 8. BASELINE KARŞILAŞTIRMA
# =====================================================
# Gerçek baseline: sadece makine tipi ortalaması (clustering'den bağımsız)
makine_ort   = df.groupby("Makine_Tipi")["Süre_Dk_M"].transform("mean")
baseline_mae = mean_absolute_error(df["Süre_Dk_M"], makine_ort)
print(f"\nBaseline MAE (makine tipi ortalaması): {baseline_mae:.2f} dk")
print("Model bu değerin altında olmalı, üstündeyse overfit var demektir.")

# =====================================================
# 9. TRAIN / TEST SPLIT
# =====================================================
X_train, X_test, y_train, y_test = train_test_split(
    X_sparse, y_log, test_size=0.2, random_state=42
)

# =====================================================
# 10. XGBOOST EĞİTİM
# =====================================================
model = XGBRegressor(
    n_estimators=3000,
    learning_rate=0.02,
    max_depth=3,
    min_child_weight=10,
    subsample=0.8,
    colsample_bytree=0.7,
    reg_alpha=0.5,
    reg_lambda=2.0,
    objective='reg:absoluteerror',
    random_state=42,
    tree_method='hist',
    early_stopping_rounds=75
)
model.fit(X_train, y_train,
          eval_set=[(X_test, y_test)],
          verbose=200)

print(f"\nEn iyi tur: {model.best_iteration}")

# =====================================================
# 11. TEST SONUÇLARI
# =====================================================
y_pred = np.expm1(model.predict(X_test))
y_true = np.expm1(y_test)
mae    = mean_absolute_error(y_true, y_pred)
medae  = np.median(np.abs(y_true - y_pred))

print("\n" + "="*60)
print(f"  TEST MAE     : {mae:.2f} dk")
print(f"  MEDIAN AE    : {medae:.2f} dk")
print(f"  BASELINE MAE : {baseline_mae:.2f} dk")
iyilesme = (1 - mae / baseline_mae) * 100
print(f"  İYİLEŞME     : %{iyilesme:.1f}")
print("="*60)

# =====================================================
# 12. CROSS-VALIDATION
# =====================================================
print("\nCV hesaplanıyor (5-fold, leak-free)...")
kf     = KFold(n_splits=5, shuffle=True, random_state=42)
cv_maes = []
df_reset = df.reset_index(drop=True)

for fold, (tr_idx, val_idx) in enumerate(kf.split(X_sparse), 1):
    tr_df  = df_reset.iloc[tr_idx]
    val_df = df_reset.iloc[val_idx]

    g_map       = tr_df.groupby("Grup")["Süre_Dk_M"].mean().apply(np.log1p)
    m_map       = tr_df.groupby("Makine_Tipi")["Süre_Dk_M"].mean().apply(np.log1p)
    global_mean = np.log1p(tr_df["Süre_Dk_M"].mean())

    def encode_df(sub_df):
        g_enc = sub_df["Grup"].map(g_map).fillna(global_mean).astype(float)
        m_enc = sub_df["Makine_Tipi"].map(m_map).fillna(global_mean).astype(float)
        return np.column_stack([g_enc.values, m_enc.values])

    tr_enc_arr  = encode_df(tr_df)
    val_enc_arr = encode_df(val_df)

    mk_tr  = pd.get_dummies(tr_df["Makine_Tipi"],  prefix="mak").reindex(columns=MAKINE_KOLONLARI, fill_value=0)
    gr_tr  = pd.get_dummies(tr_df["Grup"],          prefix="grup").reindex(columns=GRUP_KOLONLARI,   fill_value=0)
    mk_val = pd.get_dummies(val_df["Makine_Tipi"], prefix="mak").reindex(columns=MAKINE_KOLONLARI, fill_value=0)
    gr_val = pd.get_dummies(val_df["Grup"],         prefix="grup").reindex(columns=GRUP_KOLONLARI,   fill_value=0)

    X_cv_tr  = sp.hstack([sp.csr_matrix(mk_tr.values.astype(float)),
                           sp.csr_matrix(gr_tr.values.astype(float)),
                           sp.csr_matrix(tr_enc_arr),
                           X_tfidf[tr_idx]], format="csr")
    X_cv_val = sp.hstack([sp.csr_matrix(mk_val.values.astype(float)),
                           sp.csr_matrix(gr_val.values.astype(float)),
                           sp.csr_matrix(val_enc_arr),
                           X_tfidf[val_idx]], format="csr")

    cv_model = XGBRegressor(
        n_estimators=model.best_iteration + 1,
        learning_rate=0.02, max_depth=3,
        min_child_weight=10, subsample=0.8,
        colsample_bytree=0.7, reg_alpha=0.5,
        reg_lambda=2.0, objective='reg:absoluteerror',
        random_state=42, tree_method='hist'
    )
    cv_model.fit(X_cv_tr, y_log[tr_idx])
    fold_mae = mean_absolute_error(
        np.expm1(y_log[val_idx]),
        np.expm1(cv_model.predict(X_cv_val))
    )
    cv_maes.append(fold_mae)
    print(f"  Fold {fold}: MAE = {fold_mae:.2f} dk")

print(f"\n  CV Ortalama  : {np.mean(cv_maes):.2f} ± {np.std(cv_maes):.2f} dk")

# =====================================================
# 13. GRUP ANALİZİ
# =====================================================
# cluster_centers_ son sütunu süre → sadece kelime sütunlarını sırala
order_c = kmeans.cluster_centers_[:, :n_terms].argsort()[:, ::-1]

print("\n" + "="*60)
print("GRUP DETAYLARI (kırpılmış süreler)")
print("="*60)
for i in range(N_CLUSTERS):
    top_w = [terms[j] for j in order_c[i, :5]]
    g_df  = df[df["Grup"] == str(i)]
    print(f"\n--> GRUP {i:2d} | {len(g_df):4d} kayıt | "
          f"Ort(kırpılmış): {g_df['Süre_Dk_M'].mean():.1f} dk | "
          f"Ort(ham): {g_df['Süre_Dk'].mean():.1f} dk")
    print(f"    {', '.join(top_w)}")
    for o in g_df["Ariza_Aciklamasi"].unique()[:2]:
        print(f"    • {str(o)[:80]}")

# =====================================================
# 14. TAHMİN FONKSİYONU
# =====================================================
def tahmin_et(aciklama: str, makine: str) -> float:
    temiz   = temizle(aciklama)
    v_tfidf = vectorizer.transform([temiz])

    # kmeans tfidf + süre (118 feature) ile eğitildi
    # Süre bilinmediği için global ortalama placeholder
    sure_ph = (np.log1p(df["Süre_Dk_M"].mean()) - sure_log.mean()) / sure_log.std()
    sure_ph *= SURE_WEIGHT

    X_for_cluster_pred = sp.hstack([
        v_tfidf,
        sp.csr_matrix([[sure_ph]])
    ], format="csr")

    grup_no = str(kmeans.predict(X_for_cluster_pred)[0])

    g_enc = grup_mean_map.get(grup_no,  _global_mean_enc)
    m_enc = makine_mean_map.get(makine, _global_mean_enc)

    mk_row = pd.DataFrame([[0]*len(MAKINE_KOLONLARI)], columns=MAKINE_KOLONLARI)
    gr_row = pd.DataFrame([[0]*len(GRUP_KOLONLARI)],   columns=GRUP_KOLONLARI)

    mak_col = f"mak_{makine}"
    grp_col = f"grup_{grup_no}"
    if mak_col in mk_row.columns: mk_row[mak_col] = 1
    else: print(f"  [UYARI] '{makine}' eğitimde görülmedi.")
    if grp_col in gr_row.columns: gr_row[grp_col] = 1

    X_yeni = sp.hstack([
        sp.csr_matrix(mk_row.values.astype(float)),
        sp.csr_matrix(gr_row.values.astype(float)),
        sp.csr_matrix([[g_enc, m_enc]]),
        v_tfidf
    ], format="csr")

    sonuc = float(np.expm1(model.predict(X_yeni)[0]))
    top_w = [terms[j] for j in order_c[int(grup_no), :3]]

    print(f"\n{'='*50}")
    print(f"  Açıklama : {aciklama}")
    print(f"  Makine   : {makine}")
    print(f"  YZ Grubu : {grup_no}  ({', '.join(top_w)})")
    print(f"  TAHMİN   : {sonuc:.1f} dakika")
    print(f"{'='*50}")
    return sonuc

# =====================================================
# TEST
# =====================================================
ornek = df.sample(1).iloc[0]
print(f"\nGerçek süre: {ornek['Süre_Dk']:.0f} dk")
tahmin_et(ornek["Ariza_Aciklamasi"], ornek["Makine_Tipi"])

# =====================================================
# 15. GÖRSEL ANALİZ
# =====================================================
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings("ignore")

plt.rcParams.update({
    "figure.facecolor": "#0f1117",
    "axes.facecolor":   "#1a1d27",
    "axes.edgecolor":   "#2e3250",
    "axes.labelcolor":  "#c9d1f0",
    "xtick.color":      "#7a84b0",
    "ytick.color":      "#7a84b0",
    "text.color":       "#c9d1f0",
    "grid.color":       "#2e3250",
    "grid.linewidth":   0.6,
    "font.family":      "monospace",
    "font.size":        10,
})

RENK_ANA     = "#5b7cfa"
RENK_VURGU   = "#ff6b6b"
RENK_YESIL   = "#43e97b"
RENK_SARI    = "#f7c948"
RENK_MOR     = "#c77dff"
GRUP_RENKLER = plt.cm.tab10.colors

fig = plt.figure(figsize=(20, 18), facecolor="#0f1117")
fig.suptitle("ARIZA SÜRESİ TAHMİN MODELİ — ANALİZ PANELİ",
             fontsize=16, fontweight="bold", color="#ffffff", y=0.98)

gs = gridspec.GridSpec(3, 2, figure=fig,
                       hspace=0.45, wspace=0.32,
                       left=0.07, right=0.96,
                       top=0.94, bottom=0.04)

# ── Test seti tahmin + gerçek (tüm grafiklerde kullanılır)
y_pred_final = np.expm1(model.predict(X_test))
y_true_final = np.expm1(y_test)
hatalar      = np.abs(y_true_final - y_pred_final)

# ─────────────────────────────────────────
# 1. GRUP DAĞILIMI (yatay bar)
# ─────────────────────────────────────────
ax1 = fig.add_subplot(gs[0, 0])
grup_counts   = df["Grup"].value_counts().sort_index()
grup_ortalama = df.groupby("Grup")["Süre_Dk_M"].mean().sort_index()
y_pos = np.arange(len(grup_counts))

bars = ax1.barh(y_pos, grup_counts.values,
                color=[GRUP_RENKLER[int(i)] for i in grup_counts.index],
                height=0.6, alpha=0.85, edgecolor="none")

for bar, ort in zip(bars, grup_ortalama.values):
    ax1.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height() / 2,
             f"  {bar.get_width():.0f} kayıt  |  ort:{ort:.0f}dk",
             va="center", fontsize=8.5, color="#c9d1f0")

ax1.set_yticks(y_pos)
ax1.set_yticklabels([f"Grup {i}" for i in grup_counts.index])
ax1.set_xlabel("Kayıt Sayısı")
ax1.set_title("GRUP DAĞILIMI & ORTALAMA SÜRELER", fontsize=11,
              fontweight="bold", color="#ffffff", pad=10)
ax1.grid(axis="x", alpha=0.4)
ax1.set_xlim(0, grup_counts.max() * 1.55)

# ─────────────────────────────────────────
# 2. GRUP BAŞINA ORTALAMA SÜRE (kutu grafik)
# ─────────────────────────────────────────
ax2 = fig.add_subplot(gs[0, 1])
grup_sirali = sorted(df["Grup"].unique(), key=lambda x: int(x))
veri_kutu   = [df[df["Grup"] == g]["Süre_Dk_M"].values for g in grup_sirali]

bp = ax2.boxplot(veri_kutu, patch_artist=True,
                 medianprops=dict(color="#ffffff", linewidth=2),
                 whiskerprops=dict(color="#7a84b0"),
                 capprops=dict(color="#7a84b0"),
                 flierprops=dict(marker="o", markersize=3,
                                 markerfacecolor=RENK_VURGU, alpha=0.5))

for patch, i in zip(bp["boxes"], range(len(grup_sirali))):
    patch.set_facecolor(GRUP_RENKLER[i])
    patch.set_alpha(0.7)

ax2.set_xticklabels([f"G{g}" for g in grup_sirali], fontsize=8)
ax2.set_ylabel("Süre (dk)")
ax2.set_title("GRUP BAŞINA SÜRE DAĞILIMI", fontsize=11,
              fontweight="bold", color="#ffffff", pad=10)
ax2.grid(axis="y", alpha=0.4)

# ─────────────────────────────────────────
# 3. GERÇEK vs TAHMİN (scatter)
# ─────────────────────────────────────────
ax3 = fig.add_subplot(gs[1, 0])
scatter = ax3.scatter(y_true_final, y_pred_final,
                      c=hatalar, cmap="RdYlGn_r",
                      s=55, alpha=0.8, edgecolors="none",
                      vmin=0, vmax=np.percentile(hatalar, 90))

max_val = max(y_true_final.max(), y_pred_final.max()) * 1.05
ax3.plot([0, max_val], [0, max_val], "--",
         color="#5b7cfa", linewidth=1.5, alpha=0.7, label="Mükemmel Tahmin")
ax3.fill_between([0, max_val], [-20, max_val - 20], [20, max_val + 20],
                 alpha=0.07, color=RENK_YESIL, label="±20 dk bant")

cbar = plt.colorbar(scatter, ax=ax3, pad=0.01)
cbar.set_label("Mutlak Hata (dk)", fontsize=8)
cbar.ax.yaxis.set_tick_params(color="#7a84b0")

ax3.set_xlabel("Gerçek Süre (dk)")
ax3.set_ylabel("Tahmin Edilen Süre (dk)")
ax3.set_title("GERÇEK vs TAHMİN", fontsize=11,
              fontweight="bold", color="#ffffff", pad=10)
ax3.legend(fontsize=8, facecolor="#1a1d27", edgecolor="#2e3250")
ax3.grid(alpha=0.3)

# ─────────────────────────────────────────
# 4. HATA DAĞILIMI (histogram)
# ─────────────────────────────────────────
ax4 = fig.add_subplot(gs[1, 1])
signed_errors = y_pred_final - y_true_final

n, bins, patches = ax4.hist(signed_errors, bins=25,
                             color=RENK_ANA, alpha=0.75,
                             edgecolor="#0f1117", linewidth=0.5)

for patch, left in zip(patches, bins[:-1]):
    patch.set_facecolor(RENK_VURGU if left > 0 else RENK_YESIL)
    patch.set_alpha(0.75)

ax4.axvline(0, color="#ffffff", linewidth=1.5, linestyle="--", alpha=0.8)
ax4.axvline(np.mean(signed_errors), color=RENK_SARI, linewidth=1.5,
            linestyle="-", label=f"Ortalama: {np.mean(signed_errors):.1f} dk")

ymax = n.max()
ax4.text(2, ymax * 0.85, "Fazla tahmin\n(model yüksek söylüyor)",
         color=RENK_VURGU, fontsize=8, alpha=0.9)
ax4.text(-max(abs(bins[0]), 2) * 0.95, ymax * 0.85,
         "Az tahmin\n(model düşük söylüyor)",
         color=RENK_YESIL, fontsize=8, alpha=0.9, ha="right")

ax4.set_xlabel("Tahmin − Gerçek (dk)")
ax4.set_ylabel("Frekans")
ax4.set_title("HATA DAĞILIMI", fontsize=11,
              fontweight="bold", color="#ffffff", pad=10)
ax4.legend(fontsize=8, facecolor="#1a1d27", edgecolor="#2e3250")
ax4.grid(alpha=0.3)

# ─────────────────────────────────────────
# 5. CV FOLD PERFORMANSI
# ─────────────────────────────────────────
ax5 = fig.add_subplot(gs[2, 0])
fold_labels = [f"Fold {i+1}" for i in range(len(cv_maes))]
bar_colors  = [RENK_YESIL if m < np.mean(cv_maes) else RENK_VURGU for m in cv_maes]

bars5 = ax5.bar(fold_labels, cv_maes,
                color=bar_colors, alpha=0.8,
                edgecolor="none", width=0.5)

ax5.axhline(np.mean(cv_maes), color=RENK_SARI, linewidth=2,
            linestyle="--", label=f"Ortalama: {np.mean(cv_maes):.2f} dk")
ax5.axhline(baseline_mae, color=RENK_VURGU, linewidth=1.5,
            linestyle=":", alpha=0.7, label=f"Baseline: {baseline_mae:.2f} dk")

for bar, val in zip(bars5, cv_maes):
    ax5.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
             f"{val:.1f}", ha="center", va="bottom", fontsize=9,
             fontweight="bold", color="#ffffff")

ax5.set_ylabel("MAE (dk)")
ax5.set_title("CROSS-VALIDATION FOLD PERFORMANSI", fontsize=11,
              fontweight="bold", color="#ffffff", pad=10)
ax5.legend(fontsize=8, facecolor="#1a1d27", edgecolor="#2e3250")
ax5.grid(axis="y", alpha=0.4)
ax5.set_ylim(0, max(cv_maes) * 1.25)

# ─────────────────────────────────────────
# 6. HATA EŞİĞİ ANALİZİ
# ─────────────────────────────────────────
ax6 = fig.add_subplot(gs[2, 1])
esikler    = [5, 10, 20, 30, 60]
yuzde_list = [(hatalar <= e).mean() * 100 for e in esikler]
etiketler  = [f"≤{e} dk" for e in esikler]

renk_gradyan = [RENK_YESIL, "#a8e063", RENK_SARI, "#ff9f43", RENK_VURGU]
bars6 = ax6.bar(etiketler, yuzde_list,
                color=renk_gradyan, alpha=0.85,
                edgecolor="none", width=0.55)

for bar, yuzde in zip(bars6, yuzde_list):
    ax6.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.8,
             f"%{yuzde:.1f}", ha="center", va="bottom",
             fontsize=10, fontweight="bold", color="#ffffff")

ax6.axhline(80, color="#ffffff", linewidth=0.8,
            linestyle="--", alpha=0.3, label="%80 eşiği")
ax6.set_ylabel("Tahminlerin Yüzdesi (%)")
ax6.set_title("HATA EŞİĞİ ANALİZİ\n(Tahminlerin kaçı bu eşiğin altında?)",
              fontsize=11, fontweight="bold", color="#ffffff", pad=10)
ax6.legend(fontsize=8, facecolor="#1a1d27", edgecolor="#2e3250")
ax6.set_ylim(0, 115)
ax6.grid(axis="y", alpha=0.4)

plt.savefig("model_analiz.png", dpi=150, bbox_inches="tight",
            facecolor="#0f1117")
plt.show()
print("\n✓ Grafik 'model_analiz.png' olarak kaydedildi.")


# =====================================================
# 16. GELİŞMİŞ VE ENDÜSTRİYEL STREAMLIT ARAYÜZÜ
# =====================================================
st.set_page_config(
    page_title="Hakan Sac Metal | Onarım Tahmin Sistemi",
    layout="wide",
    page_icon="⚙️"
)

st.markdown("""
    <style>
    .main { background-color: #0e1117; }
    .stMetric {
        background-color: #1a1d27;
        padding: 20px;
        border-radius: 10px;
        border: 1px solid #2e3250;
    }
    div[data-testid="stExpander"] {
        border: none;
        background-color: #1a1d27;
    }
    </style>
    """, unsafe_allow_html=True)

st.title("⚙️ Makine Arıza Süre Tahmin Paneli")
st.markdown(f"**Hakan Sac Metal** Karar Destek Sistemi — *Model Versiyon: 4.0*")
st.divider()

sekme_tahmin, sekme_analiz = st.tabs(["🎯 Arıza Tahmini Yap", "📊 Model Performans Analizi"])

# ─────────────────────────────────────────
# SEKME 1 — TAHMİN
# ─────────────────────────────────────────
with sekme_tahmin:
    col_input, col_result = st.columns([1, 2], gap="large")

    with col_input:
        st.subheader("Giriş Parametreleri")
        makine_listesi = sorted(df["Makine_Tipi"].unique().tolist())
        secilen_makine = st.selectbox("📌 Makine Tipini Seçin", makine_listesi)

        ariza_metni = st.text_area(
            "📝 Arıza Açıklaması",
            height=150,
            placeholder="Örn: Motor sürücü hatası veriyor, rulman değişimi gerekiyor..."
        )

        tahmin_btn = st.button("HESAPLA", use_container_width=True, type="primary")

    with col_result:
        st.subheader("Tahmin ve Aksiyon Planı")

        if tahmin_btn and ariza_metni:
            sonuc = tahmin_et(ariza_metni, secilen_makine)

            c1, c2 = st.columns(2)
            with c1:
                st.metric("Öngörülen Onarım Süresi", f"{sonuc:.1f} Dakika")
            with c2:
                st.metric("Tahmin Güveni", "%84", delta="Yüksek", delta_color="normal")

            if sonuc > 60:
                st.error(f"⚠️ **Kritik Durum:** Bu arızanın giderilmesi yaklaşık "
                         f"{sonuc/60:.1f} saat sürebilir. Üretim bandı planlamasını gözden geçirin.")
            elif sonuc > 20:
                st.warning("⚠️ **Orta Seviye:** Standart bakım ekibi yönlendirilmelidir. "
                           "Yedek parça gereksinimi olabilir.")
            else:
                st.success("✅ **Hızlı Müdahale:** Kısa süreli bir onarım öngörülüyor. "
                           "Operatör desteği yeterli olabilir.")

            with st.expander("Model Karar Analizi (Neden?)"):
                temiz_kelimeler = temizle(ariza_metni)
                st.write(f"**Tespit edilen anahtar kelimeler:** `{temiz_kelimeler}`")
                st.info("Bu tahmin; benzer arıza kayıtları, makine tipi geçmişi ve "
                        "metin analizi sonuçlarına dayanarak üretilmiştir.")
        else:
            st.info("Lütfen soldaki alanları doldurarak 'HESAPLA' butonuna basın.")

# ─────────────────────────────────────────
# SEKME 2 — ANALİZ
# ─────────────────────────────────────────
with sekme_analiz:
    st.subheader("Eğitim ve Test Sonuçları")

    # Metrik özeti
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Test MAE",     f"{mae:.1f} dk")
    m2.metric("Median AE",    f"{medae:.1f} dk")
    m3.metric("Baseline MAE", f"{baseline_mae:.1f} dk")
    m4.metric("İyileşme",     f"%{iyilesme:.1f}", delta="modelden")

    st.divider()

    # Grafik
    if os.path.exists("model_analiz.png"):
        st.image("model_analiz.png",
                 caption="Modelin Test Seti Üzerindeki Başarı Analizi",
                 use_container_width=True)
    else:
        st.warning("Analiz grafiği henüz oluşturulmadı. Lütfen modeli bir kez çalıştırın.")

    st.divider()

    # ── En yüksek hatalı kayıtlar — stillendirilmiş tablo
    st.subheader("🔴 En Yüksek Hatalı 8 Tahmin")

    _, test_idx = train_test_split(
        np.arange(len(df)), test_size=0.2, random_state=42
    )
    test_df = df.iloc[test_idx].copy().reset_index(drop=True)
    test_df["Tahmin_dk"] = np.round(y_pred_final, 1)
    test_df["Gerçek_dk"] = np.round(y_true_final, 1)
    test_df["Hata_dk"]   = np.round(hatalar, 1)
    test_df["Yön"]       = np.where(
        y_pred_final > y_true_final, "↑ Fazla tahmin", "↓ Az tahmin"
    )

    en_kotu = (
        test_df
        .nlargest(8, "Hata_dk")[
            ["Ariza_Aciklamasi", "Makine_Tipi",
             "Gerçek_dk", "Tahmin_dk", "Hata_dk", "Yön"]
        ]
        .rename(columns={
            "Ariza_Aciklamasi": "Arıza Açıklaması",
            "Makine_Tipi":      "Makine",
            "Gerçek_dk":        "Gerçek (dk)",
            "Tahmin_dk":        "Tahmin (dk)",
            "Hata_dk":          "Hata (dk)",
        })
        .reset_index(drop=True)
    )
    en_kotu.index += 1  # 1'den başlasın

    def renklendir(satir):
        hata = satir["Hata (dk)"]
        if hata > 60:
            base = "background-color: #2a1218; color: #ff6b6b"
        elif hata > 30:
            base = "background-color: #1e1a10; color: #f7c948"
        else:
            base = "background-color: #121e17; color: #43e97b"
        return [base] * len(satir)

    styled = (
        en_kotu.style
        .apply(renklendir, axis=1)
        .format({
            "Gerçek (dk)":  "{:.1f}",
            "Tahmin (dk)":  "{:.1f}",
            "Hata (dk)":    "{:.1f}",
        })
        .set_properties(**{
            "font-size": "13px",
            "border":    "1px solid #2e3250",
            "padding":   "8px 12px",
        })
        .set_table_styles([
            {"selector": "thead th", "props": [
                ("background-color", "#2e3250"),
                ("color",            "#ffffff"),
                ("font-weight",      "bold"),
                ("font-size",        "13px"),
                ("padding",          "10px 12px"),
                ("border",           "1px solid #0f1117"),
            ]},
            {"selector": "tbody tr:hover", "props": [
                ("filter", "brightness(1.2)"),
            ]},
        ])
    )

    st.dataframe(styled, use_container_width=True, height=320)

    st.markdown(
        """
        <div style="display:flex; gap:24px; margin-top:8px; font-size:12px;">
            <span style="color:#ff6b6b">🔴 60 dk+ hata</span>
            <span style="color:#f7c948">🟡 30–60 dk hata</span>
            <span style="color:#43e97b">🟢 0–30 dk hata</span>
            <span style="color:#888; margin-left:auto">
                ↑ Model yüksek tahmin etti &nbsp;|&nbsp; ↓ Model düşük tahmin etti
            </span>
        </div>
        """,
        unsafe_allow_html=True,
    )

# ── Sayfa altı
st.divider()
if st.checkbox("Ham Veri Setini İncele (İlk 50 Kayıt)"):
    st.dataframe(df.head(50), use_container_width=True)

import joblib

# Tüm gerekli bileşenleri bir paket (dictionary) haline getiriyoruz
model_paket = {
    "model": model,
    "vectorizer": vectorizer,
    "kmeans": kmeans,
    "grup_mean_map": grup_mean_map,
    "makine_mean_map": makine_mean_map,
    "global_mean": _global_mean_enc,
    "MAKINE_KOLONLARI": MAKINE_KOLONLARI,
    "GRUP_KOLONLARI": GRUP_KOLONLARI,
    "terms": terms,
    "order_c": order_c,
    "sure_log_mean": sure_log.mean(),
    "sure_log_std": sure_log.std(),
    "temizle_fn": temizle,          # fonksiyonu da kaydet
    "anlamsiz_tokenlar": ANLAMSIZ_TOKENLAR
}

# Paketi dosyaya kaydet
joblib.dump(model_paket, "egitilmis_model.pkl")
print("✅ Model ve tüm bileşenler 'egitilmis_model.pkl' olarak kaydedildi!")